# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_dialog.ui'
#
# Created: Sun Oct  3 14:06:25 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(597, 569)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.inp_Pwd = QtGui.QLineEdit(Dialog)
        self.inp_Pwd.setObjectName("inp_Pwd")
        self.horizontalLayout.addWidget(self.inp_Pwd)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setEnabled(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.spinbox_char_num = QtGui.QSpinBox(self.groupBox)
        self.spinbox_char_num.setMinimum(3)
        self.spinbox_char_num.setMaximum(1024)
        self.spinbox_char_num.setProperty("value", 8)
        self.spinbox_char_num.setObjectName("spinbox_char_num")
        self.horizontalLayout_7.addWidget(self.spinbox_char_num)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.chbox_use_digits = QtGui.QCheckBox(self.groupBox)
        self.chbox_use_digits.setEnabled(True)
        self.chbox_use_digits.setChecked(True)
        self.chbox_use_digits.setObjectName("chbox_use_digits")
        self.verticalLayout_3.addWidget(self.chbox_use_digits)
        self.chbox_use_letters = QtGui.QCheckBox(self.groupBox)
        self.chbox_use_letters.setEnabled(True)
        self.chbox_use_letters.setChecked(True)
        self.chbox_use_letters.setObjectName("chbox_use_letters")
        self.verticalLayout_3.addWidget(self.chbox_use_letters)
        self.chbox_use_symbols = QtGui.QCheckBox(self.groupBox)
        self.chbox_use_symbols.setEnabled(True)
        self.chbox_use_symbols.setChecked(True)
        self.chbox_use_symbols.setObjectName("chbox_use_symbols")
        self.verticalLayout_3.addWidget(self.chbox_use_symbols)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.groupBox_Symbols = QtGui.QGroupBox(Dialog)
        self.groupBox_Symbols.setEnabled(True)
        self.groupBox_Symbols.setObjectName("groupBox_Symbols")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_Symbols)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.chbox_use_exclam = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_exclam.setEnabled(True)
        self.chbox_use_exclam.setChecked(True)
        self.chbox_use_exclam.setObjectName("chbox_use_exclam")
        self.gridLayout.addWidget(self.chbox_use_exclam, 0, 0, 1, 1)
        self.chbox_use_db_quotes = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_db_quotes.setEnabled(True)
        self.chbox_use_db_quotes.setChecked(True)
        self.chbox_use_db_quotes.setObjectName("chbox_use_db_quotes")
        self.gridLayout.addWidget(self.chbox_use_db_quotes, 1, 0, 1, 1)
        self.chbox_use_number_sign = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_number_sign.setEnabled(True)
        self.chbox_use_number_sign.setChecked(True)
        self.chbox_use_number_sign.setObjectName("chbox_use_number_sign")
        self.gridLayout.addWidget(self.chbox_use_number_sign, 2, 0, 1, 1)
        self.chbox_use_dollar = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_dollar.setEnabled(True)
        self.chbox_use_dollar.setChecked(True)
        self.chbox_use_dollar.setObjectName("chbox_use_dollar")
        self.gridLayout.addWidget(self.chbox_use_dollar, 3, 0, 1, 1)
        self.chbox_use_percent = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_percent.setEnabled(True)
        self.chbox_use_percent.setChecked(True)
        self.chbox_use_percent.setObjectName("chbox_use_percent")
        self.gridLayout.addWidget(self.chbox_use_percent, 4, 0, 1, 1)
        self.chbox_use_ampersand = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_ampersand.setEnabled(True)
        self.chbox_use_ampersand.setChecked(True)
        self.chbox_use_ampersand.setObjectName("chbox_use_ampersand")
        self.gridLayout.addWidget(self.chbox_use_ampersand, 5, 0, 1, 1)
        self.chbox_use_single_quote = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_single_quote.setEnabled(True)
        self.chbox_use_single_quote.setChecked(True)
        self.chbox_use_single_quote.setObjectName("chbox_use_single_quote")
        self.gridLayout.addWidget(self.chbox_use_single_quote, 6, 0, 1, 1)
        self.chbox_use_open_parenthesis = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_open_parenthesis.setEnabled(True)
        self.chbox_use_open_parenthesis.setChecked(True)
        self.chbox_use_open_parenthesis.setObjectName("chbox_use_open_parenthesis")
        self.gridLayout.addWidget(self.chbox_use_open_parenthesis, 7, 0, 1, 1)
        self.chbox_use_close_parenthesis = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_close_parenthesis.setEnabled(True)
        self.chbox_use_close_parenthesis.setChecked(True)
        self.chbox_use_close_parenthesis.setObjectName("chbox_use_close_parenthesis")
        self.gridLayout.addWidget(self.chbox_use_close_parenthesis, 8, 0, 1, 1)
        self.chbox_use_asterisk = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_asterisk.setEnabled(True)
        self.chbox_use_asterisk.setChecked(True)
        self.chbox_use_asterisk.setObjectName("chbox_use_asterisk")
        self.gridLayout.addWidget(self.chbox_use_asterisk, 9, 0, 1, 1)
        self.chbox_use_plus = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_plus.setEnabled(True)
        self.chbox_use_plus.setChecked(True)
        self.chbox_use_plus.setObjectName("chbox_use_plus")
        self.gridLayout.addWidget(self.chbox_use_plus, 10, 0, 1, 1)
        self.chbox_use_comma = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_comma.setEnabled(True)
        self.chbox_use_comma.setChecked(True)
        self.chbox_use_comma.setObjectName("chbox_use_comma")
        self.gridLayout.addWidget(self.chbox_use_comma, 0, 1, 1, 1)
        self.chbox_use_minus = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_minus.setEnabled(True)
        self.chbox_use_minus.setChecked(True)
        self.chbox_use_minus.setObjectName("chbox_use_minus")
        self.gridLayout.addWidget(self.chbox_use_minus, 1, 1, 1, 1)
        self.chbox_use_period = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_period.setEnabled(True)
        self.chbox_use_period.setChecked(True)
        self.chbox_use_period.setObjectName("chbox_use_period")
        self.gridLayout.addWidget(self.chbox_use_period, 2, 1, 1, 1)
        self.chbox_use_slash = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_slash.setEnabled(True)
        self.chbox_use_slash.setChecked(True)
        self.chbox_use_slash.setObjectName("chbox_use_slash")
        self.gridLayout.addWidget(self.chbox_use_slash, 3, 1, 1, 1)
        self.chbox_use_colon = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_colon.setEnabled(True)
        self.chbox_use_colon.setChecked(True)
        self.chbox_use_colon.setObjectName("chbox_use_colon")
        self.gridLayout.addWidget(self.chbox_use_colon, 4, 1, 1, 1)
        self.chbox_use_semicolon = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_semicolon.setEnabled(True)
        self.chbox_use_semicolon.setChecked(True)
        self.chbox_use_semicolon.setObjectName("chbox_use_semicolon")
        self.gridLayout.addWidget(self.chbox_use_semicolon, 5, 1, 1, 1)
        self.chbox_use_less = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_less.setEnabled(True)
        self.chbox_use_less.setChecked(True)
        self.chbox_use_less.setObjectName("chbox_use_less")
        self.gridLayout.addWidget(self.chbox_use_less, 6, 1, 1, 1)
        self.chbox_use_equal = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_equal.setEnabled(True)
        self.chbox_use_equal.setChecked(True)
        self.chbox_use_equal.setObjectName("chbox_use_equal")
        self.gridLayout.addWidget(self.chbox_use_equal, 7, 1, 1, 1)
        self.chbox_use_greater = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_greater.setEnabled(True)
        self.chbox_use_greater.setChecked(True)
        self.chbox_use_greater.setObjectName("chbox_use_greater")
        self.gridLayout.addWidget(self.chbox_use_greater, 8, 1, 1, 1)
        self.chbox_use_question = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_question.setEnabled(True)
        self.chbox_use_question.setChecked(True)
        self.chbox_use_question.setObjectName("chbox_use_question")
        self.gridLayout.addWidget(self.chbox_use_question, 9, 1, 1, 1)
        self.chbox_use_at = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_at.setEnabled(True)
        self.chbox_use_at.setChecked(True)
        self.chbox_use_at.setObjectName("chbox_use_at")
        self.gridLayout.addWidget(self.chbox_use_at, 10, 1, 1, 1)
        self.chbox_use_open_bracket = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_open_bracket.setEnabled(True)
        self.chbox_use_open_bracket.setChecked(True)
        self.chbox_use_open_bracket.setObjectName("chbox_use_open_bracket")
        self.gridLayout.addWidget(self.chbox_use_open_bracket, 0, 2, 1, 1)
        self.chbox_use_backslash = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_backslash.setEnabled(True)
        self.chbox_use_backslash.setChecked(True)
        self.chbox_use_backslash.setObjectName("chbox_use_backslash")
        self.gridLayout.addWidget(self.chbox_use_backslash, 1, 2, 1, 1)
        self.chbox_use_close_bracket = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_close_bracket.setEnabled(True)
        self.chbox_use_close_bracket.setChecked(True)
        self.chbox_use_close_bracket.setObjectName("chbox_use_close_bracket")
        self.gridLayout.addWidget(self.chbox_use_close_bracket, 2, 2, 1, 1)
        self.chbox_use_caret = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_caret.setEnabled(True)
        self.chbox_use_caret.setChecked(True)
        self.chbox_use_caret.setObjectName("chbox_use_caret")
        self.gridLayout.addWidget(self.chbox_use_caret, 3, 2, 1, 1)
        self.chbox_use_underscore = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_underscore.setEnabled(True)
        self.chbox_use_underscore.setChecked(True)
        self.chbox_use_underscore.setObjectName("chbox_use_underscore")
        self.gridLayout.addWidget(self.chbox_use_underscore, 4, 2, 1, 1)
        self.chbox_use_grave_accent = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_grave_accent.setEnabled(True)
        self.chbox_use_grave_accent.setChecked(True)
        self.chbox_use_grave_accent.setObjectName("chbox_use_grave_accent")
        self.gridLayout.addWidget(self.chbox_use_grave_accent, 5, 2, 1, 1)
        self.chbox_use_open_brace = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_open_brace.setEnabled(True)
        self.chbox_use_open_brace.setChecked(True)
        self.chbox_use_open_brace.setObjectName("chbox_use_open_brace")
        self.gridLayout.addWidget(self.chbox_use_open_brace, 6, 2, 1, 1)
        self.chbox_use_vertical_bar = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_vertical_bar.setEnabled(True)
        self.chbox_use_vertical_bar.setChecked(True)
        self.chbox_use_vertical_bar.setObjectName("chbox_use_vertical_bar")
        self.gridLayout.addWidget(self.chbox_use_vertical_bar, 7, 2, 1, 1)
        self.chbox_use_close_brace = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_close_brace.setEnabled(True)
        self.chbox_use_close_brace.setChecked(True)
        self.chbox_use_close_brace.setObjectName("chbox_use_close_brace")
        self.gridLayout.addWidget(self.chbox_use_close_brace, 8, 2, 1, 1)
        self.chbox_use_tilde = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_tilde.setEnabled(True)
        self.chbox_use_tilde.setChecked(True)
        self.chbox_use_tilde.setObjectName("chbox_use_tilde")
        self.gridLayout.addWidget(self.chbox_use_tilde, 9, 2, 1, 1)
        self.chbox_use_space = QtGui.QCheckBox(self.groupBox_Symbols)
        self.chbox_use_space.setEnabled(True)
        self.chbox_use_space.setChecked(True)
        self.chbox_use_space.setObjectName("chbox_use_space")
        self.gridLayout.addWidget(self.chbox_use_space, 10, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        self.horizontalLayout_4.addWidget(self.groupBox_Symbols)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_About = QtGui.QPushButton(Dialog)
        self.btn_About.setObjectName("btn_About")
        self.horizontalLayout_2.addWidget(self.btn_About)
        self.btn_GenNewPwd = QtGui.QPushButton(Dialog)
        self.btn_GenNewPwd.setObjectName("btn_GenNewPwd")
        self.horizontalLayout_2.addWidget(self.btn_GenNewPwd)
        self.btn_Quit = QtGui.QPushButton(Dialog)
        self.btn_Quit.setObjectName("btn_Quit")
        self.horizontalLayout_2.addWidget(self.btn_Quit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.chbox_use_symbols, QtCore.SIGNAL("toggled(bool)"), self.groupBox_Symbols.setEnabled)
        QtCore.QObject.connect(self.btn_Quit, QtCore.SIGNAL("clicked(bool)"), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "PyPassword Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Generate a pasword with the selected criterias", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.inp_Pwd.setToolTip(QtGui.QApplication.translate("Dialog", "Generated password", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Password length:", None, QtGui.QApplication.UnicodeUTF8))
        self.spinbox_char_num.setToolTip(QtGui.QApplication.translate("Dialog", "Enter a number from 3 to 1024", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_digits.setText(QtGui.QApplication.translate("Dialog", "Use digits [0-9]", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_letters.setText(QtGui.QApplication.translate("Dialog", "Use letters [a-zA-Z]", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_symbols.setText(QtGui.QApplication.translate("Dialog", "Use special symbols", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_Symbols.setTitle(QtGui.QApplication.translate("Dialog", "Special symbols", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_exclam.setText(QtGui.QApplication.translate("Dialog", "!", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_db_quotes.setText(QtGui.QApplication.translate("Dialog", "\"", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_number_sign.setText(QtGui.QApplication.translate("Dialog", "#", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_dollar.setText(QtGui.QApplication.translate("Dialog", "$", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_percent.setText(QtGui.QApplication.translate("Dialog", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_ampersand.setText(QtGui.QApplication.translate("Dialog", "&&", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_single_quote.setText(QtGui.QApplication.translate("Dialog", "\'", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_open_parenthesis.setText(QtGui.QApplication.translate("Dialog", "(", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_close_parenthesis.setText(QtGui.QApplication.translate("Dialog", ")", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_asterisk.setText(QtGui.QApplication.translate("Dialog", "*", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_plus.setText(QtGui.QApplication.translate("Dialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_comma.setText(QtGui.QApplication.translate("Dialog", ",", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_minus.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_period.setText(QtGui.QApplication.translate("Dialog", ".", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_slash.setText(QtGui.QApplication.translate("Dialog", "/", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_colon.setText(QtGui.QApplication.translate("Dialog", ":", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_semicolon.setText(QtGui.QApplication.translate("Dialog", ";", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_less.setText(QtGui.QApplication.translate("Dialog", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_equal.setText(QtGui.QApplication.translate("Dialog", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_greater.setText(QtGui.QApplication.translate("Dialog", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_question.setText(QtGui.QApplication.translate("Dialog", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_at.setText(QtGui.QApplication.translate("Dialog", "@", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_open_bracket.setText(QtGui.QApplication.translate("Dialog", "[", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_backslash.setText(QtGui.QApplication.translate("Dialog", "\\", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_close_bracket.setText(QtGui.QApplication.translate("Dialog", "]", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_caret.setText(QtGui.QApplication.translate("Dialog", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_underscore.setText(QtGui.QApplication.translate("Dialog", "_", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_grave_accent.setText(QtGui.QApplication.translate("Dialog", "`", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_open_brace.setText(QtGui.QApplication.translate("Dialog", "{", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_vertical_bar.setText(QtGui.QApplication.translate("Dialog", "|", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_close_brace.setText(QtGui.QApplication.translate("Dialog", "}", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_tilde.setText(QtGui.QApplication.translate("Dialog", "~", None, QtGui.QApplication.UnicodeUTF8))
        self.chbox_use_space.setText(QtGui.QApplication.translate("Dialog", "space", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_About.setToolTip(QtGui.QApplication.translate("Dialog", "Press this button to generate a new password", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_About.setText(QtGui.QApplication.translate("Dialog", "About...", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_GenNewPwd.setToolTip(QtGui.QApplication.translate("Dialog", "Press this button to generate a new password", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_GenNewPwd.setText(QtGui.QApplication.translate("Dialog", "Generate new password", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_Quit.setToolTip(QtGui.QApplication.translate("Dialog", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_Quit.setText(QtGui.QApplication.translate("Dialog", "Quit", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

